name: Build

on:
  release:
  workflow_dispatch:

jobs:
  build-linux-armv5:
    name: linux/armv5
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Build
        run: |
          docker run --platform linux/arm/v5 -i -v $PWD:/ws debian:stable bash << EOF
          set -xeu
          cd /ws
          apt update; apt -y install libx11-dev xorg-dev xutils-dev build-essential autoconf musl xcb libxcb-util-dev libxau-dev x11proto-dev libxdmcp-dev libxau6
          ./autogen.sh
          ./configure --enable-static
          make
          mv ico ico-dvd
          chmod +x ico-dvd
          EOF
      -
        name: Prepare go-bin-deb
        run: |
          wget https://github.com/mh-cbon/go-bin-deb/releases/download/0.0.19/go-bin-deb-amd64.deb && \
          sudo apt -y install ./go-bin-deb-amd64.deb && \
          rm go-bin-deb-amd64.deb && \
          sudo chmod +x ico-dvd && \
          go-bin-deb generate --file .github/workflows/deb.json --wd . --version 0.0.1 --arch armel

      -
        name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            ico-dvd
            *.deb

      -
        name: Prepare packaging & packagecloud CLI
        run: |
          sudo apt update
          sudo apt install debhelper ruby-dev
          sudo gem install package_cloud

      -
        name: Upload the package to packagecloud
        env:
          USERNAME: brainhackers
          REPO: brainux/any/any
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: |
          package_cloud push "${USERNAME}/${REPO}" `ls *.deb`
